enum Response{
  signUpSuccess,
  emailAlreadyExist,
  usernameAlreadyExist,
  logInSuccess,
  userNotFound,
  incorrectPassword,
  logOutSuccess,
  profileUpdateSuccess,
  profileUpdateFailed,
  passwordUpdateSuccess,
  passwordUpdateFailed,
  uploadMusicSuccess,
  error,
  InvalidRequest,
  USER_ALREADY_EXIST,
}